"""
MACDXStrategy - Deterministic MACD Crossover Strategy.

MACDX mode works WITHOUT AI. All signals are generated by the deterministic
signal generator based on MACD crossover with multiple confirmations.

This strategy class is minimal - it provides documentation context only,
since no AI calls are made in MACDX mode.
"""

from src.prompts.strategies.base import BaseStrategy


class MACDXStrategy(BaseStrategy):

    def get_role(self) -> str:
        return "Deterministic MACD Crossover trader. No AI involvement - pure technical signals."

    def get_objective(self) -> str:
        return "Execute trades based on MACD crossover with 3-5 indicator confirmations. No AI analysis."

    def get_time_horizon(self) -> str:
        return "Configurable timeframe (default: 5m). Holds depend on market conditions and exit signals."

    def get_strategy_section(self, ctx: dict) -> str:
        """
        This is only called for logging/debugging purposes.
        MACDX mode does NOT invoke AI, so this prompt is not actually used.
        """
        signal_data = ctx.get("signal_data") or {}
        signal = signal_data.get("signal", "HOLD")
        score = signal_data.get("score", 0)
        max_score = signal_data.get("max_score", 9)
        quality = signal_data.get("quality", 0.0)
        confirmations = signal_data.get("confirmations", 0)
        reasons = signal_data.get("reasons", [])
        details = signal_data.get("details", {})

        # Market context
        current_price = ctx.get("current_price", 0)
        rsi = ctx.get("rsi", 50)
        volume_ratio = ctx.get("volume_ratio", 1.0)

        reasons_str = "\n".join(f"  - {r}" for r in reasons) if reasons else "  - No reasons"

        return f"""## 3. STRATEGY: MACDX (NO-AI DETERMINISTIC)

**IMPORTANT:** This strategy operates WITHOUT AI involvement.
All trading decisions are made by the deterministic signal generator.

---

### SIGNAL GENERATOR OUTPUT

| Parameter | Value |
|-----------|-------|
| **Signal** | **{signal}** |
| **Score** | {score}/{max_score} |
| **Quality** | {quality:.2f} |
| **Confirmations** | {confirmations}/5 |

**Signal Reasons:**
{reasons_str}

---

### CONFIRMATION INDICATORS

1. **MACD Crossover** (Required): Line crosses signal line
2. **RSI Zone**: Not overbought for long, not oversold for short
3. **EMA Alignment**: Short EMA confirms direction
4. **Not Sideways**: Market has directional movement (BB width / ADX)
5. **No Exhaustion**: No RSI divergence against direction
6. **Volume**: Sufficient volume to support move

---

### CURRENT MARKET STATE

| Indicator | Value |
|-----------|-------|
| Price | {current_price:.2f} |
| RSI | {rsi:.1f} |
| Volume | {volume_ratio:.2f}x |
| MACD Hist | {details.get('macd_hist', 0):.4f} |
| BB Width | {details.get('bb_width', 0):.1f}% |
| Is Sideways | {"Yes" if details.get('is_sideways') else "No"} |

---

### TRADE EXECUTION

This is a fully automated strategy:
- **Entry**: When MACD crossover + minimum 3 confirmations
- **Exit**: MACD reversal, RSI extreme, or SL/TP hit
- **No AI**: All decisions are deterministic

**NOTE:** This prompt exists for documentation only. No AI calls are made."""

    def get_position_management(self, ctx: dict) -> str:
        """Position management docs for MACDX."""
        return """### POSITION MANAGEMENT (MACDX)

Exit signals are deterministic:
1. MACD histogram reverses against position
2. RSI reaches extreme (>80 for long, <20 for short)
3. Take profit triggered at good PnL + momentum fade
4. Stop loss hit (ATR-based)

All exits are automatic - no AI involvement."""

    def get_special_situations(self, ctx: dict) -> str:
        """Special situations docs for MACDX."""
        return """### WHEN TO SKIP SIGNALS

The signal generator automatically filters:
1. **Low volatility**: ATR ratio < threshold
2. **Low volume**: Volume ratio < minimum
3. **Sideways market**: Narrow BB + low ADX
4. **RSI exhaustion**: Against signal direction
5. **Insufficient confirmations**: Less than 3 of 5 confirmations

### WHEN TO TAKE SIGNALS

Execute when:
1. MACD crossover detected
2. At least 3/5 confirmations present
3. Score >= minimum threshold
4. No hard filters triggered

This is fully automatic - no manual or AI intervention."""
